config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :companies
  devise_for :users

  resources :users, only: [:index, :show, :profile, :perfil]

  root 'static_pages#home'

  resources :posts

  get 'profile', to: 'users#profile', as: :profile
  get 'follow/:id', to: 'users#follow', as: :follow
  get 'endorse/:id', to: 'users#endorse', as: :endorse

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/company.rb
class Company < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
    validates :title, presence: true, length: { minimum: 3 }
    validates :body, presence: true, length: { minimum: 30 }
end

app/models/user.rb
class User < ActiveRecord::Base

has_many :posts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_followable
  acts_as_follower
  


has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" },
    :default_url => "/images/:style/missing.png",
    :url  => ":s3_domain_url",
    :path => "public/avatars/:id/:style_:basename.:extension",
    :storage => :fog,
    :fog_credentials => {
        provider: 'AWS',
        aws_access_key_id: ENV["AWS_ACCESS_KEY_ID"],
        aws_secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"]
    },
    fog_directory: ENV["FOG_DIRECTORY"]

    do_not_validate_attachment_file_type :avatar

  def full_name
    if self.name.blank?
      self.email
    else
      self.name
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.


 protect_from_forgery with: :exception
    before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
        devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :is_female, :date_of_birth, :avatar, :location, :description, :lookingfor) }
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_filter :authenticate_user!, except: [:show, :index]
	
	def index
		@posts = Post.all
	end
	def show
		@post = Post.find(params[:id])
	end
	def new
		@post = Post.new
	end

  def create

    @user = current_user
    @post = @user.posts.build(allowed_params)

    if @post.save
      flash[:success] = "Created new post"
      redirect_to @post
    else
      render 'new'
    end
  end

    private
        def allowed_params
            params.require(:post).permit(:title, :body)
        end
 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!, except: [:index, :endorse]

  def index
    @users = User.all
  end
  def show
    @user = User.find(params[:id])
  end
  def profile
    @user = User.find(current_user)
  end
  def follow
    @user_to_follow = User.find(params[:id])
  	@user = User.find(current_user)
	
	 if @user.follow(@user_to_follow) # Creates a record for the user as the follower and the book as the followable
      flash[:success] = "NEW FOLLOW!"
      redirect_to :controller => 'users', :action => 'profile'
    else
      flash[:alert] = "No follow"
      redirect_to :controller => 'users', :action => 'profile'
    end
  end
  def endorse
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
    <html>
        <head>
            <title>TheDemo</title>
            <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
            <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
            <%= csrf_meta_tags %>
            
        </head>

        <body>

            <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %> alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <%= value %>
            </div>
            <% end %>


            <nav class="navbar navbar-default" role="navigation">
                <div class="container">

                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <%= link_to "Demo App", root_path, class: 'navbar-brand' %>
                    </div>
                    
                    <div class="collapse navbar-collapse" id="navbar-collapse-1">

                        <ul class="nav navbar-nav navbar-right">

                            <li><%= link_to 'My Profile', profile_path %></li>
                            <% if current_user %>
                                <li><%= link_to 'Edit Profile',edit_user_registration_path %></li>
                                <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
                            <% else %>
                                <li><%= link_to 'Login', new_user_session_path %></li>
                                <li><%= link_to 'Im a Company', new_company_session_path %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="container">
                <%= yield %>
            </div>

        </body>
    </html>

app/views/posts/index.html.erb
	<ul>
        <% @posts.each do |p| %>
            <li>
                <h3><%= link_to p.title, post_path(p.id) %></h3>
                <p><small><strong>By: </strong><%= p.user.email  if p.user %></small></p>
                <p><%= p.body %></p>
            </li>
        <% end %>
    </ul>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
<%= render 'shared/error_messages', object: f.object %>
        <div class="form-group">
            <%= f.label :title, class: 'control-label' %>
            <%= f.text_field :title, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= f.label :body, class: 'control-label' %>
            <%= f.text_area :body, class: 'form-control', rows: 6 %>
        </div>

        <%= f.submit 'Save', class: 'btn btn-primary' %>
    <% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
    <p><small><strong>By: </strong><%= @post.user.email %></small></p>
    <p><%= @post.body %></p>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <p><strong>This form contains <%= pluralize(object.errors.count, 'errors') %>.</strong></p>
            <ul>
                <% object.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    </div>
<% end %>

app/views/static_pages/home.html.erb
<h1>This is the home page</h1>

app/views/users/endorse.html.erb
<h3><%= @user.email %> needs your help!</h3>
<div class="row-fluid">
  <div class="col-md-12 text-center">
    <div class="thumbnail">
      <%= image_tag(@user.avatar.url(:medium), class: 'avatar') %>
      <div class="caption">
        <h5>Do you want to endorse <span class="black-text"><%= @user.email %></span>???</h5>
        <p>Your endorse will leverage the profile! With one click you can </p>
        

        <% if current_user %>
	        <%= button_to "endorse", follow_path(@user.id), class: "btn-default", :method => :get unless @user.following?(User.find(current_user)) %>
	    <% else %>
	        <%= button_to "endorse", follow_path(@user.id), class: "btn-default", :method => :get %>
	    <% end %>

      </div>
    </div>
  </div>
</div>

app/views/users/follow.html.erb
<br>New follow!

app/views/users/index.html.erb
<div class="container">
    <div class="users row">
        <% @users.each do |user| %>
        <div class="panel panel-default">
            <%= link_to user_path(user) do %>
            <div class="panel-body">
                <%= image_tag(user.avatar.url(:medium)) %>
                <p><%= user.full_name %></p>
            </div>
            <% end %>
        </div>
        <% end %>
    </div>
</div>

app/views/users/profile.html.erb
   
            
<div class="row profile">
    <div class="col-sm-4 col-md-3">
         <div class="form-group">
        <%= image_tag(@user.avatar.url(:medium), class: 'avatar') %>
    </div>
    <div class="form-group">
        <h3><%= @user.email %></h3>
    </div>
    <div class="form-group">
        <%= content_tag(:li, ("Age: " + distance_of_time_in_words(Time.now, @user.date_of_birth) + " old")) unless @user.date_of_birth.blank? %>
    </div>
    <div class="form-group">
        <%= content_tag(:li, ("Email: " + @user.email)) unless @user.email.blank? %>
    </div>   
    <div class="form-group">
        <%= content_tag(:li, ("location: " + @user.location)) unless @user.location.blank? %>
    </div>   
     <div class="form-group">
        <%= content_tag(:li, ("lookingfor: " + @user.lookingfor)) unless @user.lookingfor.blank? %>
    </div>  
    <div class="form-group">
        <li>Total endorsers: <%= @user.followers_count %></li>
    </div>  
       
    </div>
    <div class="feed">
        <div class='panel-endorse'>
            <h3>Get more endorsers!</h3>
            <div class="input-group">
                <span class="input-group-addon">Link to share with friends</span>
                <input type="text" class="form-control" <%= 'value='+'http://'+request.host_with_port+ endorse_path(@user.id)+'-'+@user.email %>>
            </div>
        </div>
        <table class="table table-striped">
            <% @user.followers.each do |f| %>
                <tr>
                  <td><%= image_tag(f.avatar.url(:thumb), class: 'avatar')%></td>
                  <td><%= f.full_name %><br><%= f.email %></td>
                </tr>  
            <% end %>
        </table>
    </div>
</div>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div class="row profile">
    <div class="col-sm-4 col-md-3">
        <%= image_tag(@user.avatar.url(:medium), class: 'avatar') %>
        <h1><%= @user.full_name %></h1>
        <ul>
            <%= content_tag(:li, ("Name: " + @user.name)) unless @user.name.blank? %>
            <%= content_tag(:li, ("Age: " + distance_of_time_in_words(Time.now, @user.date_of_birth) + " old")) unless @user.date_of_birth.blank? %>
            <%= content_tag(:li, ("Email: " + @user.email)) unless @user.email.blank? %>
        </ul>
        <%= link_to "Endorse!", follow_path(@user.id) %>
    </div>
    <div class="feed">
        <h3>Endorsers: <%= @user.followers_count %></h3>
        <table class="table table-striped">
            <% @user.followers.each do |f| %>
                <tr>
                  <td><%= f.id %></td>
                  <td><%= f.email %></td>
                </tr>  
            <% end %>
        </table>
    </div>
</div>